
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('catalogo.paises').del()
    .then(function () {
      // Inserts seed entries
      return knex('catalogo.paises').insert([
        { codigoInternacional: '101', codigoNacional: '2', descripcion: 'Albania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '102', codigoNacional: '14', descripcion: 'Austria', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '103', codigoNacional: '20', descripcion: 'Bélgica', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '104', codigoNacional: '31', descripcion: 'Bulgaria', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '106', codigoNacional: '42', descripcion: 'Chipre', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '107', codigoNacional: '53', descripcion: 'Dinamarca', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '108', codigoNacional: '64', descripcion: 'España', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '109', codigoNacional: '71', descripcion: 'Finlandia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '110', codigoNacional: '72', descripcion: 'Francia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '111', codigoNacional: '79', descripcion: 'Grecia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '112', codigoNacional: '93', descripcion: 'Hungría', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '113', codigoNacional: '98', descripcion: 'Irlanda', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '114', codigoNacional: '101', descripcion: 'Islandia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '115', codigoNacional: '116', descripcion: 'Italia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '116', codigoNacional: '132', descripcion: 'Liechtenstein', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '117', codigoNacional: '134', descripcion: 'Luxemburgo', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '118', codigoNacional: '141', descripcion: 'Malta', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '119', codigoNacional: '149', descripcion: 'Mónaco', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '120', codigoNacional: '162', descripcion: 'Noruega', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '121', codigoNacional: '166', descripcion: 'Países Bajos', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '122', codigoNacional: '175', descripcion: 'Polonia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '123', codigoNacional: '176', descripcion: 'Portugal', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '124', codigoNacional: '4', descripcion: 'Andorra', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '125', codigoNacional: '179', descripcion: 'Reino Unido', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '126', codigoNacional: '3', descripcion: 'Alemania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '128', codigoNacional: '189', descripcion: 'Rumanía', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '129', codigoNacional: '198', descripcion: 'San Marino', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '130', codigoNacional: '242', descripcion: 'Santa Sede', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '131', codigoNacional: '216', descripcion: 'Suecia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '132', codigoNacional: '217', descripcion: 'Suiza', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '135', codigoNacional: '232', descripcion: 'Ucrania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '136', codigoNacional: '128', descripcion: 'Letonia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '137', codigoNacional: '183', descripcion: 'Moldavia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '138', codigoNacional: '243', descripcion: 'Belarús', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '139', codigoNacional: '75', descripcion: 'Georgia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '141', codigoNacional: '67', descripcion: 'Estonia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '142', codigoNacional: '133', descripcion: 'Lituania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '143', codigoNacional: '182', descripcion: 'República Checa', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '144', codigoNacional: '62', descripcion: 'República Eslovaca', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '145', codigoNacional: '27', descripcion: 'Bosnia y Herzegovina', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '146', codigoNacional: '50', descripcion: 'Croacia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '147', codigoNacional: '63', descripcion: 'Eslovenia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '148', codigoNacional: '11', descripcion: 'Armenia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '154', codigoNacional: '190', descripcion: 'Rusia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '156', codigoNacional: '126', descripcion: 'Macedonia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '157', codigoNacional: '206', descripcion: 'Serbia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '158', codigoNacional: '151', descripcion: 'Montenegro', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '199', codigoNacional: '994', descripcion: 'Otros países de Europa', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '201', codigoNacional: '32', descripcion: 'Burkina Faso', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '202', codigoNacional: '5', descripcion: 'Angola', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '203', codigoNacional: '9', descripcion: 'Argelia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '204', codigoNacional: '22', descripcion: 'Benin', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '205', codigoNacional: '28', descripcion: 'Botswana', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '206', codigoNacional: '33', descripcion: 'Burundi', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '207', codigoNacional: '244', descripcion: 'Cabo Verde', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '208', codigoNacional: '37', descripcion: 'Camerún', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '209', codigoNacional: '245', descripcion: 'Comores', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '210', codigoNacional: '45', descripcion: 'Congo', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '211', codigoNacional: '48', descripcion: 'Costa de Marfil', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '212', codigoNacional: '54', descripcion: 'Djibouti', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '213', codigoNacional: '57', descripcion: 'Egipto', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '214', codigoNacional: '68', descripcion: 'Etiopía', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '215', codigoNacional: '73', descripcion: 'Gabón', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '216', codigoNacional: '74', descripcion: 'Gambia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '217', codigoNacional: '76', descripcion: 'Ghana', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '218', codigoNacional: '87', descripcion: 'Guinea', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '219', codigoNacional: '88', descripcion: 'Guinea-Bissau', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '220', codigoNacional: '86', descripcion: 'Guinea Ecuatorial', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '221', codigoNacional: '246', descripcion: 'Kenia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '222', codigoNacional: '247', descripcion: 'Lesotho', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '223', codigoNacional: '130', descripcion: 'Liberia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '224', codigoNacional: '131', descripcion: 'Libia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '225', codigoNacional: '136', descripcion: 'Madagascar', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '226', codigoNacional: '138', descripcion: 'Malawi', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '227', codigoNacional: '140', descripcion: 'Mali', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '228', codigoNacional: '142', descripcion: 'Marruecos', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '229', codigoNacional: '144', descripcion: 'Mauricio', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '230', codigoNacional: '145', descripcion: 'Mauritania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '231', codigoNacional: '153', descripcion: 'Mozambique', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '232', codigoNacional: '155', descripcion: 'Namibia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '233', codigoNacional: '159', descripcion: 'Níger', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '234', codigoNacional: '160', descripcion: 'Nigeria', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '235', codigoNacional: '181', descripcion: 'República Centroafricana', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '236', codigoNacional: '213', descripcion: 'Sudáfrica', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '237', codigoNacional: '248', descripcion: 'Ruanda', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '238', codigoNacional: '203', descripcion: 'Santo Tomé y Príncipe', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '239', codigoNacional: '205', descripcion: 'Senegal', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '240', codigoNacional: '207', descripcion: 'Seychelles', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '241', codigoNacional: '208', descripcion: 'Sierra Leona', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '242', codigoNacional: '211', descripcion: 'Somalia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '243', codigoNacional: '214', descripcion: 'Sudán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '244', codigoNacional: '220', descripcion: 'Swazilandia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '245', codigoNacional: '187', descripcion: 'Tanzania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '246', codigoNacional: '39', descripcion: 'Chad', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '247', codigoNacional: '224', descripcion: 'Togo', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '248', codigoNacional: '228', descripcion: 'Túnez', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '249', codigoNacional: '233', descripcion: 'Uganda', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '250', codigoNacional: '184', descripcion: 'República Democrática del Congo', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '251', codigoNacional: '240', descripcion: 'Zambia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '252', codigoNacional: '241', descripcion: 'Zimbabwe', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '253', codigoNacional: '61', descripcion: 'Eritrea', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '254', codigoNacional: '215', descripcion: 'Sudán del Sur', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '299', codigoNacional: '995', descripcion: 'Otros países de África', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '301', codigoNacional: '38', descripcion: 'Canadá', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '302', codigoNacional: '66', descripcion: 'Estados Unidos de América', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '303', codigoNacional: '147', descripcion: 'México', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '310', codigoNacional: '7', descripcion: 'Antigua y Barbuda', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '311', codigoNacional: '16', descripcion: 'Bahamas', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '312', codigoNacional: '19', descripcion: 'Barbados', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '313', codigoNacional: '21', descripcion: 'Belice', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '314', codigoNacional: '49', descripcion: 'Costa Rica', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '315', codigoNacional: '51', descripcion: 'Cuba', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '316', codigoNacional: '55', descripcion: 'Dominica', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '317', codigoNacional: '58', descripcion: 'El Salvador', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '318', codigoNacional: '78', descripcion: 'Granada', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '319', codigoNacional: '83', descripcion: 'Guatemala', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '320', codigoNacional: '90', descripcion: 'Haití', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '321', codigoNacional: '91', descripcion: 'Honduras', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '322', codigoNacional: '117', descripcion: 'Jamaica', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '323', codigoNacional: '158', descripcion: 'Nicaragua', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '324', codigoNacional: '169', descripcion: 'Panamá', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '325', codigoNacional: '200', descripcion: 'San Vicente y las Granadinas', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '326', codigoNacional: '186', descripcion: 'República Dominicana', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '327', codigoNacional: '227', descripcion: 'Trinidad y Tobago', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '328', codigoNacional: '202', descripcion: 'Santa Lucía', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '329', codigoNacional: '197', descripcion: 'San Cristóbal y Nieves', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '340', codigoNacional: '10', descripcion: 'Argentina', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '341', codigoNacional: '25', descripcion: 'Bolivia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '342', codigoNacional: '29', descripcion: 'Brasil', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '343', codigoNacional: '43', descripcion: 'Colombia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '344', codigoNacional: '40', descripcion: 'Chile', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '345', codigoNacional: '56', descripcion: 'Ecuador', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '346', codigoNacional: '89', descripcion: 'Guyana', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '347', codigoNacional: '171', descripcion: 'Paraguay', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '348', codigoNacional: '172', descripcion: 'Perú', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '349', codigoNacional: '218', descripcion: 'Surinam', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '350', codigoNacional: '234', descripcion: 'Uruguay', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '351', codigoNacional: '237', descripcion: 'Venezuela', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '399', codigoNacional: '996', descripcion: 'Otros países de América', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '401', codigoNacional: '1', descripcion: 'Afganistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '402', codigoNacional: '8', descripcion: 'Arabia Saudí', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '403', codigoNacional: '17', descripcion: 'Bahréin', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '404', codigoNacional: '18', descripcion: 'Bangladesh', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '405', codigoNacional: '154', descripcion: 'Myanmar', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '407', codigoNacional: '41', descripcion: 'China', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '408', codigoNacional: '60', descripcion: 'Emiratos Árabes Unidos', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '409', codigoNacional: '70', descripcion: 'Filipinas', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '410', codigoNacional: '94', descripcion: 'India', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '411', codigoNacional: '95', descripcion: 'Indonesia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '412', codigoNacional: '96', descripcion: 'Iraq', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '413', codigoNacional: '97', descripcion: 'Irán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '414', codigoNacional: '115', descripcion: 'Israel', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '415', codigoNacional: '118', descripcion: 'Japón', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '416', codigoNacional: '120', descripcion: 'Jordania', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '417', codigoNacional: '36', descripcion: 'Camboya', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '418', codigoNacional: '125', descripcion: 'Kuwait', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '419', codigoNacional: '185', descripcion: 'Laos', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '420', codigoNacional: '129', descripcion: 'Líbano', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '421', codigoNacional: '137', descripcion: 'Malasia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '422', codigoNacional: '139', descripcion: 'Maldivas', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '423', codigoNacional: '150', descripcion: 'Mongolia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '424', codigoNacional: '157', descripcion: 'Nepal', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '425', codigoNacional: '165', descripcion: 'Omán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '426', codigoNacional: '167', descripcion: 'Pakistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '427', codigoNacional: '178', descripcion: 'Qatar', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '430', codigoNacional: '47', descripcion: 'Corea del Sur', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '431', codigoNacional: '46', descripcion: 'Corea del Norte', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '432', codigoNacional: '209', descripcion: 'Singapur', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '433', codigoNacional: '180', descripcion: 'Siria', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '434', codigoNacional: '212', descripcion: 'Sri Lanka', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '435', codigoNacional: '221', descripcion: 'Tailandia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '436', codigoNacional: '230', descripcion: 'Turquía', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '437', codigoNacional: '238', descripcion: 'Vietnam', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '439', codigoNacional: '249', descripcion: 'Brunei', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '440', codigoNacional: '109', descripcion: 'Islas Marshall', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '441', codigoNacional: '239', descripcion: 'Yemen', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '442', codigoNacional: '15', descripcion: 'Azerbaiyán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '443', codigoNacional: '121', descripcion: 'Kazajstán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '444', codigoNacional: '123', descripcion: 'Kirguistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '445', codigoNacional: '250', descripcion: 'Tayikistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '446', codigoNacional: '229', descripcion: 'Turkmenistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '447', codigoNacional: '235', descripcion: 'Uzbekistán', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '448', codigoNacional: '251', descripcion: 'Bhután', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '449', codigoNacional: '65', descripcion: 'Palestina. Estado Observador, no miembro de Naciones Unidas', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '499', codigoNacional: '997', descripcion: 'Otros países de Asia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '501', codigoNacional: '13', descripcion: 'Australia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '502', codigoNacional: '252', descripcion: 'Fiji', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '504', codigoNacional: '164', descripcion: 'Nueva Zelanda', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '505', codigoNacional: '170', descripcion: 'Papúa Nueva Guinea', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '506', codigoNacional: '110', descripcion: 'Islas Salomón', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '507', codigoNacional: '195', descripcion: 'Samoa', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '508', codigoNacional: '226', descripcion: 'Tonga', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '509', codigoNacional: '236', descripcion: 'Vanuatu', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '511', codigoNacional: '148', descripcion: 'Micronesia', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '512', codigoNacional: '231', descripcion: 'Tuvalu', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '513', codigoNacional: '104', descripcion: 'Islas Cook', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '514', codigoNacional: '124', descripcion: 'Kiribati', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '515', codigoNacional: '156', descripcion: 'Nauru', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '516', codigoNacional: '253', descripcion: 'Palaos', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '517', codigoNacional: '254', descripcion: 'Timor Oriental', idEstadoRegistro: 2, idCredencialIngreso: 1 }, 
{ codigoInternacional: '599', codigoNacional: '998', descripcion: 'Otros países de Oceanía', idEstadoRegistro: 2, idCredencialIngreso: 1 }
      ]);
    });
};
